import { z } from 'zod';
import {
  commonDefinition,
  nonNegativeInt,
  nonNegativeNumber,
  positiveInt,
  positiveNumber,
} from './common';

const enemyBase = {
  ...commonDefinition,
  id: z.string().regex(/^enemy\./, 'enemy id must start with enemy.'),
  hp: positiveNumber,
  radius: positiveNumber,
  score: nonNegativeInt,
  jackpotGain: nonNegativeNumber,
  scrapDrops: z.array(z.enum(['normal', 'heavy', 'jackpot'])).default([]),
  contributionPoints: nonNegativeInt,
};

export const enemySchema = z.discriminatedUnion('type', [
  z.object({
    ...enemyBase,
    type: z.literal('scrapBug'),
    speed: positiveNumber,
    damage: positiveNumber,
    hitCooldown: positiveNumber,
    circleDistance: positiveNumber,
    circleStrength: positiveNumber,
    separationDistance: positiveNumber,
    separationStrength: positiveNumber,
    obstacleAvoidTurn: positiveNumber,
    speedWobbleAmplitude: nonNegativeNumber,
    speedWobbleFrequency: positiveNumber,
    ramSpeedThreshold: nonNegativeNumber,
    ramScore: nonNegativeInt,
    ramKnockback: nonNegativeNumber,
  }),
  z.object({
    ...enemyBase,
    type: z.literal('rammer'),
    approachSpeed: positiveNumber,
    chargeSpeed: positiveNumber,
    damage: positiveNumber,
    telegraphTime: positiveNumber,
    chargeTime: positiveNumber,
    recoveryTime: positiveNumber,
    lockTime: nonNegativeNumber,
    lockDistance: positiveNumber,
    dodgeDistance: positiveNumber,
    knockback: nonNegativeNumber,
    recoveryDecel: positiveNumber,
    rearBonus: positiveNumber,
  }),
  z.object({
    ...enemyBase,
    type: z.literal('gunTower'),
    damage: positiveNumber,
    shotSpeed: positiveNumber,
    shotInterval: positiveNumber,
    shotCount: positiveInt,
    firePause: nonNegativeNumber,
    telegraphTime: positiveNumber,
    trackRate: positiveNumber,
    idleTime: nonNegativeNumber,
    aimJitter: nonNegativeNumber,
    muzzleOffsetX: nonNegativeNumber,
    muzzleHeight: positiveNumber,
    shotLife: positiveNumber,
  }),
  z.object({
    ...enemyBase,
    type: z.literal('lootTruck'),
    speed: positiveNumber,
    spawnTime: positiveNumber,
    escapeTime: positiveNumber,
    waypointReach: positiveNumber,
    escapeShortcut: positiveNumber,
    collisionPushTank: nonNegativeNumber,
    collisionPushTruck: nonNegativeNumber,
    jackpotScrapCount: positiveInt,
    jackpotScrapLife: positiveNumber,
  }),
]);

export type EnemyDefinition = z.infer<typeof enemySchema>;
