import { z } from 'zod';

export const packManifestSchema = z.object({
  pack: z.object({
    id: z.string().regex(/^[a-z][a-z0-9-]*$/, 'pack id must be lowercase with dashes'),
    version: z.string().regex(/^\d+\.\d+\.\d+$/, 'version must be semver-like (x.y.z)'),
    mode: z.string().regex(/^mode\./, 'manifest mode must reference a mode definition'),
    files: z.object({
      modes: z.array(z.string()),
      objectives: z.array(z.string()),
      maps: z.array(z.string()),
      terrainProfiles: z.array(z.string()),
      validationProfiles: z.array(z.string()),
      landmarks: z.array(z.string()),
      furnitureSets: z.array(z.string()),
      densityProfiles: z.array(z.string()),
      tanks: z.array(z.string()),
      loadouts: z.array(z.string()),
      weapons: z.array(z.string()),
      projectiles: z.array(z.string()),
      enemies: z.array(z.string()),
      dropTables: z.array(z.string()),
      pickups: z.array(z.string()),
      items: z.array(z.string()),
      statusEffects: z.array(z.string()),
      spawnDirectors: z.array(z.string()),
      stageSequences: z.array(z.string()),
      farmingPhases: z.array(z.string()),
      hordeDirectors: z.array(z.string()),
      populationLimits: z.array(z.string()),
      spawnPacks: z.array(z.string()),
      waves: z.array(z.string()),
      bossWaves: z.array(z.string()),
      spawnAnchorPolicies: z.array(z.string()),
      hordeNavigationPolicies: z.array(z.string()),
      enemyLodPolicies: z.array(z.string()),
      hordeReplicationPolicies: z.array(z.string()),
      rewardTables: z.array(z.string()),
      scoring: z.array(z.string()),
      results: z.array(z.string()),
      difficulties: z.array(z.string()),
      presentation: z.array(z.string()),
    }),
  }),
});

export type PackManifest = z.infer<typeof packManifestSchema>;
