import type { ParameterDescriptor } from './parameterTypes';

export const furnitureParameters: ParameterDescriptor[] = [
  {
    path: 'furnitureSet.objectPlacement.enabled',
    label: 'All Objects',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'boolean',
    description: 'Master switch: turn every object off while keeping terrain, roads, spawns and gates.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.barrel.enabled',
    label: 'Explosive Barrels',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'boolean',
    description: 'Turn explosive barrels on or off.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.lightPoles.enabled',
    label: 'Light Poles',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'boolean',
    description: 'Turn the decorative light poles on or off.',
    requiresRegeneration: true,
  },
  {
    path: 'densityProfile.budgets.maxObjects',
    label: 'Object Budget',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'number',
    min: 0,
    max: 400,
    step: 10,
    description: 'Overall cap on how many objects are placed. Lower = emptier map.',
    requiresRegeneration: true,
  },
  {
    path: 'densityProfile.budgets.maxColliders',
    label: 'Solid Object Budget',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'number',
    min: 0,
    max: 300,
    step: 10,
    description: 'Cap on objects the tank can bump into. Lower = fewer walls to dodge.',
    requiresRegeneration: true,
  },
  {
    path: 'densityProfile.budgets.maxBarrelChain',
    label: 'Chain Reaction Cap',
    group: 'objects',
    subgroup: 'Master Switches',
    type: 'number',
    min: 1,
    max: 8,
    step: 1,
    advanced: true,
    description: 'The longest barrel chain reaction the validator will allow.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.barrel.count',
    label: 'How Many',
    group: 'objects',
    subgroup: 'Barrels',
    type: 'number',
    min: 0,
    max: 60,
    step: 1,
    description: 'How many barrels to try to scatter around.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.barrel.minSpacing',
    label: 'Spacing',
    group: 'objects',
    subgroup: 'Barrels',
    type: 'number',
    min: 4,
    max: 30,
    step: 1,
    unit: 'm',
    description: 'Minimum gap between barrels. Higher = safer, more spread-out barrels.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.barrel.chainRadius',
    label: 'Blast Link Range',
    group: 'objects',
    subgroup: 'Barrels',
    type: 'number',
    min: 2,
    max: 20,
    step: 1,
    unit: 'm',
    advanced: true,
    description: 'How close barrels must be to set each other off in a chain.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.barrel.maxChain',
    label: 'Max Chain Length',
    group: 'objects',
    subgroup: 'Barrels',
    type: 'number',
    min: 1,
    max: 8,
    step: 1,
    advanced: true,
    description: 'Longest barrel chain allowed on the map.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.lightPoles.count',
    label: 'How Many',
    group: 'objects',
    subgroup: 'Light Poles',
    type: 'number',
    min: 0,
    max: 40,
    step: 1,
    advanced: true,
    description: 'How many light poles to place.',
    requiresRegeneration: true,
  },
];

export function entryParameters(entryIndex: number, subgroup: string, prefix: string): ParameterDescriptor[] {
  const p = (suffix: string, label: string, type: ParameterDescriptor['type'], extra: Partial<ParameterDescriptor> = {}): ParameterDescriptor => ({
    path: `furnitureSet.entries.${entryIndex}.${suffix}`,
    label: `${prefix} ${label}`,
    group: 'objects',
    subgroup,
    type,
    requiresRegeneration: true,
    ...extra,
  });
  return [
    p('enabled', 'On/Off', 'boolean', { description: 'Place objects from this group, or skip it.' }),
    p('count', 'How Many', 'number', { min: 0, max: 100, step: 1, description: 'How many of these to try to place.' }),
    p('minSpacing', 'Spacing', 'number', { min: 1, max: 60, step: 1, unit: 'm', description: 'Minimum gap between these and other objects.' }),
    p('clearance', 'Clearance', 'number', { min: 0, max: 20, step: 0.5, unit: 'm', description: 'Keep-away zone so the tank can steer around it.' }),
    p('slopeMax', 'Steepness Limit', 'number', { min: 0.05, max: 1, step: 0.05, description: 'Steepest ground this object is allowed to sit on.' }),
    p('collider', 'Solid?', 'boolean', { description: 'Solid (the tank bumps into it) or just decoration to drive through.' }),
    p('assetId', 'Model', 'text', { description: 'Which visual model this object uses.' }),
    p('obstacleType', 'Behaves Like', 'select', {
      options: ['container', 'barrier', 'tires', 'factory', 'crusher', 'towerBase', 'scrapPile', 'wall'],
      description: 'What kind of obstacle it counts as for the game rules.',
    }),
  ];
}
