import type { ParameterDescriptor } from './parameterTypes';

export const mapParameters: ParameterDescriptor[] = [
  {
    path: 'map.widthMeters',
    label: 'Width',
    group: 'basic',
    type: 'number',
    min: 100,
    max: 1000,
    step: 100,
    unit: 'm',
    description: 'How wide the map is. Bigger = more room to roam (and more ground to cross).',
    requiresRegeneration: true,
  },
  {
    path: 'map.depthMeters',
    label: 'Depth',
    group: 'basic',
    type: 'number',
    min: 100,
    max: 1000,
    step: 100,
    unit: 'm',
    description: 'How deep (long) the map is. Same idea as Width, just the other direction.',
    requiresRegeneration: true,
  },
  {
    path: 'map.cellSize',
    label: 'Cell Size',
    group: 'terrain',
    subgroup: 'Advanced',
    type: 'number',
    min: 2,
    max: 8,
    step: 1,
    unit: 'm',
    advanced: true,
    description: 'How chunky the ground grid is. Smaller = finer detail but slower generation.',
    requiresRegeneration: true,
  },
];
