import type { ParameterDescriptor } from './parameterTypes';

export const routeParameters: ParameterDescriptor[] = [
  {
    path: 'furnitureSet.routeClearance',
    label: 'Road Clearance',
    group: 'routes',
    subgroup: 'Roads',
    type: 'number',
    min: 6,
    max: 40,
    step: 1,
    unit: 'm',
    description: 'How much open space routes keep around them so the tank has room to steer.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.routeMinHalfWidth',
    label: 'Minimum Road Width',
    group: 'routes',
    subgroup: 'Roads',
    type: 'number',
    min: 4,
    max: 40,
    step: 1,
    unit: 'm',
    description: 'How wide the roads must be. Wider = easier driving, narrower = tighter paths.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.maxRouteSlope',
    label: 'Road Steepness',
    group: 'routes',
    subgroup: 'Roads',
    type: 'number',
    min: 0.05,
    max: 1,
    step: 0.05,
    description: 'Steepest slope allowed on roads. Lower = flatter, friendlier routes.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.enabled',
    label: 'Ramps On/Off',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'boolean',
    description: 'Turn ramps on or off. Ramps let the tank catch air between hills.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.count',
    label: 'Ramp Count',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'number',
    min: 0,
    max: 12,
    step: 1,
    description: 'How many ramps to place on the map.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.length.0',
    label: 'Shortest Ramp',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'number',
    min: 4,
    max: 30,
    step: 1,
    unit: 'm',
    advanced: true,
    description: 'Shortest ramp length the generator may use.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.length.1',
    label: 'Longest Ramp',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'number',
    min: 4,
    max: 30,
    step: 1,
    unit: 'm',
    advanced: true,
    description: 'Longest ramp length the generator may use.',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.rise.0',
    label: 'Lowest Rise',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'number',
    min: 0.3,
    max: 5,
    step: 0.1,
    unit: 'm',
    advanced: true,
    description: 'Lowest ramp height (gentle ramps).',
    requiresRegeneration: true,
  },
  {
    path: 'furnitureSet.ramps.rise.1',
    label: 'Highest Rise',
    group: 'routes',
    subgroup: 'Ramps',
    type: 'number',
    min: 0.3,
    max: 5,
    step: 0.1,
    unit: 'm',
    advanced: true,
    description: 'Highest ramp height (launch-y ramps).',
    requiresRegeneration: true,
  },
];
