import type { ParameterDescriptor } from './parameterTypes';

export const validationParameters: ParameterDescriptor[] = [
  {
    path: 'validationProfile.heightRange.min',
    label: 'Lowest Allowed',
    group: 'validation',
    subgroup: 'Height Rules',
    type: 'number',
    min: -30,
    max: 0,
    step: 0.5,
    unit: 'm',
    description: 'The lowest ground height the validator will accept. Go lower to allow deeper valleys.',
    requiresRegeneration: false,
  },
  {
    path: 'validationProfile.heightRange.max',
    label: 'Highest Allowed',
    group: 'validation',
    subgroup: 'Height Rules',
    type: 'number',
    min: 0,
    max: 40,
    step: 0.5,
    unit: 'm',
    description: 'The highest ground height the validator will accept. Go higher to allow taller hills.',
    requiresRegeneration: false,
  },
  {
    path: 'validationProfile.maxSlope',
    label: 'Steepness Limit',
    group: 'validation',
    subgroup: 'Height Rules',
    type: 'number',
    min: 0.05,
    max: 1.5,
    step: 0.05,
    description: 'Steepest slope the validator accepts. Stricter = safer but harder to generate.',
    requiresRegeneration: false,
  },
  {
    path: 'validationProfile.minFeatureSeparation',
    label: 'Feature Spacing',
    group: 'validation',
    subgroup: 'Spacing & Speed',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    unit: 'm',
    description: 'How far apart terrain features must be to pass. Higher = fewer overlapping shapes.',
    requiresRegeneration: false,
  },
  {
    path: 'validationProfile.maxGenerationMs',
    label: 'Time Budget',
    group: 'validation',
    subgroup: 'Spacing & Speed',
    type: 'number',
    min: 50,
    max: 5000,
    step: 50,
    unit: 'ms',
    description: 'If generating takes longer than this, the attempt counts as failed. Lower = stricter.',
    requiresRegeneration: false,
  },
];
